trigger:
- main   # run pipeline when pushing to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m flask --app app run
  displayName: 'Run Flask App'
